version: "3.9"

services:
  db_audio:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env
    networks:
      - net

  app:
    build:
      dockerfile: ./Dockerfile
    command: ["docker/app.sh"]
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env
    volumes:
      - upload:/app/upload
    depends_on:
      - db_audio
    networks:
      - net

volumes:
  postgres_volume:
  upload:

networks:
  net:
    driver: bridge