  name: Test Code Project

  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
    workflow_dispatch:

  jobs:
    Test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.11
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip poetry
            poetry config virtualenvs.create false --local
            poetry install --no-root
        - name: Build the test BD
          run: docker compose -f docker-compose-test.yml up -d
        - name: Run tests
          run: pytest tests



